version: '3.8'

services:
  web:
    build: .
    command: gunicorn server:app -w 4 -b 0.0.0.0:80 --access-logfile - --error-logfile -
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./secure-drop:/secure-drop/files
    environment:
      FLASK_APP: server.py
      FLASK_DEBUG: ${DEBUG}
      DEBUG: ${DEBUG}
      SENDGRIDFROMEMAIL: ${SENDGRIDFROMEMAIL}
      SENDGRIDAPIKEY: ${SENDGRIDAPIKEY}
      RECAPTCHASITEKEY: ${RECAPTCHASITEKEY}
      RECAPTCHASECRETKEY: ${RECAPTCHASECRETKEY}
      TOEMAIL: ${TOEMAIL}
 


